/** @jsx React.DOM */
var Anchor = React.createClass({
    render: function() {

        /**
         * We use JQuery event binding so that its onClick event will run even when it is generated by
         * React's renderComponentToString or renderComponentToStaticMarkup.
         */
        $("#" + this.props.id).off("click");
        $("#" + this.props.id).on("click", this.linkClick);

        /**
         * Use button element since the link element and all other HTML elements (except button) and their attributes
         * show up in the filter. This is a shortcoming of jQuery Datatable 1.9.4. Please see
         * http://datatables.net/forums/discussion/20831/exclude-html-contents-classes-from-text-search.
         */

        var val = this.props.value;
        var title = "";
        if (this.props.maxDisplayTextLen !== undefined && val.length > this.props.maxDisplayTextLen) {
            title = val;
            val = val.substring(0, this.props.maxDisplayTextLen) + "...";
        }

        var className = (this.props.className === undefined ? "button-link" : "button-link " + this.props.className);
        return <button id={this.props.id} className={className} title={title}>{val}</button>
    },
    linkClick: function() {
        if ($("#" + this.props.id).hasClass("disabled")) {
            return false;
        }

        if (this.props.waitForResponse === true) {
            this.props.callback("#" + this.props.id, this.props.data);
        } else {
            this.props.callback(this.props.data);
        }

        return false;
    }
});
